name: Template
main: code.Template
version: 0.0.0
description: Nothing here yet.
author: 
api-version: 1.13

folia-supported: true

commands:

  Template:
    aliases: []
    description: No description yet.
    usage: Nope, no usage here. No.
    

